name: Android CI/CD (PR-approved only)

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      run_ci:
        description: "Run CI (build/tests)?"
        required: true
        default: "true"
      run_cd:
        description: "Run CD (distribute to Firebase)?"
        required: true
        default: "false"

jobs:
  ci:
    name: CI - Build (PR approved or manual)
    runs-on: ubuntu-latest

    if: >
      (github.event_name == 'pull_request_review' &&
       github.event.review.state == 'approved')
      ||
      (github.event_name == 'workflow_dispatch' &&
       github.event.inputs.run_ci == 'true')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      #- name: Run unit tests
       # run: ./gradlew test

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  cd:
    name: CD - Distribute
    runs-on: ubuntu-latest
    needs: ci

    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_cd == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler dependencies
        run: bundle install

      - name: Distribute APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: bundle exec fastlane android firebase
